version: '3.8'
services:
  influxdb:
    image: influxdb:${INFLUXDB_TAG}
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb:/var/lib/influxdb2
      - $PWD/config:/etc/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - influxv2.env

  telegraf:
    image: telegraf:${TELEGRAF_TAG}
    links:
      - influxdb
    ports:
      - "4317:4317"  
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - influxv2.env
    depends_on:
      - influxdb

volumes:
  influxdb:
  
